DROP TABLE IF EXISTS ods.ods_game_coinsetmeal ;
CREATE  TABLE ods.ods_game_coinsetmeal
(   id  VARCHAR(38) NOT NULL ,
  setmealname  VARCHAR(100) ,
  cointype  NUMERIC(22,10) ,
  coinnumber  NUMERIC(22,10) ,
  groupname  VARCHAR(64) ,
  goldcoinnumber  NUMERIC(22,10) ,
  cancelhours  NUMERIC(22,10) ,
  isneedauth  NUMERIC(22) ,
  isneedprint  NUMERIC(22) ,
  goodsinfo  VARCHAR(38) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  createtime  DATE ,
  intelligentpriority  NUMERIC(22,10) ,
  isforjoin  NUMERIC(22) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_game_coinsetmeal  is '电玩业态-售币套餐';
DROP TABLE IF EXISTS ods.ods_game_machine ;
CREATE  TABLE ods.ods_game_machine
(   id  VARCHAR(38) NOT NULL ,
  gametype  VARCHAR(38) ,
  machinename  VARCHAR(64) ,
  machineno  VARCHAR(64) ,
  needcoincheck  NUMERIC(22) ,
  portamount  NUMERIC(22,10) ,
  useports  VARCHAR(600) ,
  localposx  NUMERIC(22,10) ,
  localposy  NUMERIC(22,10) ,
  gateoutnumber  NUMERIC(22,10) ,
  terminal  VARCHAR(38) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  createtime  DATE ,
  groupname  VARCHAR(64) ,
  machinecode  VARCHAR(64) ,
  localproperty  VARCHAR(38) ,
  area  VARCHAR(38) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_game_machine  is '电玩业态-机台信息';
DROP TABLE IF EXISTS ods.ods_game_machinearea ;
CREATE  TABLE ods.ods_game_machinearea
(   id  VARCHAR(38) NOT NULL ,
  areaname  VARCHAR(64) ,
  areano  VARCHAR(64) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  createtime  DATE ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_game_machinearea  is '电玩业态-区域信息';
DROP TABLE IF EXISTS ods.ods_game_machinetype ;
CREATE  TABLE ods.ods_game_machinetype
(   id  VARCHAR(38) NOT NULL ,
  ticketoutdelay  NUMERIC(22,10) ,
  ticketoutspeed  NUMERIC(22,10) ,
  ticketoutwidth  NUMERIC(22,10) ,
  motorpot  NUMERIC(22) ,
  eyespot  NUMERIC(22) ,
  coininpertime  NUMERIC(22,10) ,
  coininpertime2  NUMERIC(22,10) ,
  simulationcoininspeed  NUMERIC(22,10) ,
  coininpot  NUMERIC(22) ,
  coininminspeed  NUMERIC(22,10) ,
  simulationcoininwidth  NUMERIC(22,10) ,
  sendcoinspulsepertime  NUMERIC(22,10) ,
  gamekind  NUMERIC(22,10) ,
  typename  VARCHAR(100) ,
  coinalertminvalue  NUMERIC(22,19) ,
  coinalertmaxvalue  NUMERIC(22,19) ,
  uselgvalue  VARCHAR(38) ,
  uselgvalue2  VARCHAR(38) ,
  uselgvalue3  VARCHAR(38) ,
  uselgvalue4  VARCHAR(38) ,
  timemodelpaytype  VARCHAR(38) ,
  timemodebasemoney  NUMERIC(22,19) ,
  timemodebaseminute  NUMERIC(22,10) ,
  timemodeaddminute  NUMERIC(22,10) ,
  timemodeusemoney  NUMERIC(22,19) ,
  timemodemaxmoney  NUMERIC(22,19) ,
  terminaltype  NUMERIC(22,10) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  createtime  DATE ,
  groupname  VARCHAR(64) ,
  occupiedarea  NUMERIC(22,19) ,
  ticketpot  NUMERIC(22) ,
  ticketmotorpot  NUMERIC(22) ,
  ticketoutamplificationfactor  NUMERIC(22,10) ,
  ticketouttype  NUMERIC(22,10) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_game_machinetype  is '电玩业态-机台种类';
DROP TABLE IF EXISTS ods.ods_game_machineusevalueset ;
CREATE  TABLE ods.ods_game_machineusevalueset
(   id  VARCHAR(38) NOT NULL ,
  machinetype  VARCHAR(38) ,
  lgvaluetype  NUMERIC(22,10) ,
  sort  NUMERIC(22,10) ,
  valueinpertime  NUMERIC(22,19) ,
  valueinpertime2  NUMERIC(22,19) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  createtime  DATE ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_game_machineusevalueset  is '机台消费类型设置类';
DROP TABLE IF EXISTS ods.ods_game_packageticketapportion ;
CREATE  TABLE ods.ods_game_packageticketapportion
(   id  VARCHAR(38) NOT NULL ,
  packageticket  VARCHAR(38) ,
  machine  VARCHAR(38) ,
  apportionmoney  NUMERIC(22,19) ,
  leaguer  VARCHAR(38) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  operateterminal  VARCHAR(38) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  accreditid  NUMERIC(22,19) ,
  operateemployeename  VARCHAR(64) ,
  logtime  DATE ,
  operateemployee  VARCHAR(38) ,
  inperiod  VARCHAR(38) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_game_packageticketapportion  is '套票分摊表';
DROP TABLE IF EXISTS ods.ods_mall_area ;
CREATE  TABLE ods.ods_mall_area
(   id  VARCHAR(38) NOT NULL ,
  areaname  VARCHAR(64) ,
  futureland__parent  VARCHAR(38) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_mall_area  is '套票可玩时间设置映射';
DROP TABLE IF EXISTS ods.ods_mall_areamapmall ;
CREATE  TABLE ods.ods_mall_areamapmall
(   id  VARCHAR(38) NOT NULL ,
  mall  VARCHAR(38) ,
  area  VARCHAR(38) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_mall_areamapmall  is '购物中心区域';
DROP TABLE IF EXISTS ods.ods_mall_business ;
CREATE  TABLE ods.ods_mall_business
(   id  VARCHAR(38) NOT NULL ,
  businessname  VARCHAR(64) ,
  businessnum  VARCHAR(64) ,
  businesstype  NUMERIC(22,10) ,
  address  VARCHAR(256) ,
  banknumber  VARCHAR(64) ,
  bankowner  VARCHAR(64) ,
  bankname  VARCHAR(64) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  createtime  DATE ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_mall_business  is '无';
DROP TABLE IF EXISTS ods.ods_mall_chargejoin ;
CREATE  TABLE ods.ods_mall_chargejoin
(   id  VARCHAR(38) NOT NULL ,
  setmealname  VARCHAR(64) ,
  groupname  VARCHAR(64) ,
  cashnumber  NUMERIC(22,19) ,
  addprepaid  NUMERIC(22,19) ,
  leaguerexpiredays  NUMERIC(22,10) ,
  isneedauth  NUMERIC(22) ,
  leaguerlevel  VARCHAR(38) ,
  goodsinfo  VARCHAR(38) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  createtime  DATE ,
  unitiveverifytime  DATE ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_mall_chargejoin  is '无';
DROP TABLE IF EXISTS ods.ods_mall_everydaygoodsalesnap ;
CREATE  TABLE ods.ods_mall_everydaygoodsalesnap
(   id  VARCHAR(38) NOT NULL ,
  goodsname  VARCHAR(64) ,
  goods  VARCHAR(38) ,
  goodstype  NUMERIC(22,10) ,
  amount  NUMERIC(22,19) ,
  itemcount  NUMERIC(22,10) ,
  sourcemoney  NUMERIC(22,19) ,
  sellmoney  NUMERIC(22,19) ,
  price  NUMERIC(22,19) ,
  futureland__cost  NUMERIC(22,19) ,
  fee  NUMERIC(22,19) ,
  compeletedate  DATE ,
  biztype  NUMERIC(22,10) ,
  operateterminal  VARCHAR(38) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  accreditid  NUMERIC(22,19) ,
  operateemployeename  VARCHAR(64) ,
  logtime  DATE ,
  operateemployee  VARCHAR(38) ,
  inperiod  VARCHAR(38) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  goodsgroup  VARCHAR(64) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) ,
  etl_lad_dte DATE 
) 
partition by range (etl_lad_dte) 
  ( START (date '2017-05-03') INCLUSIVE 
  END (date '2019-09-23') INCLUSIVE EVERY (INTERVAL '1 month'), 
  DEFAULT PARTITION extra);
 comment on  table ods.ods_mall_everydaygoodsalesnap  is '无';
DROP TABLE IF EXISTS ods.ods_mall_exchangeitemlog ;
CREATE  TABLE ods.ods_mall_exchangeitemlog
(   id  VARCHAR(38) NOT NULL ,
  futureland__exchange  VARCHAR(38) ,
  goods  VARCHAR(38) ,
  goodsname  VARCHAR(64) ,
  unitprice  NUMERIC(22,19) ,
  afterdiscountunitprice  NUMERIC(22,19) ,
  goodscount  NUMERIC(22,19) ,
  returngoodscount  NUMERIC(22,19) ,
  totaldiscount  NUMERIC(22,19) ,
  originaltotalprice  NUMERIC(22,19) ,
  totalcost  NUMERIC(22,19) ,
  totalfee  NUMERIC(22,19) ,
  itemstatus  NUMERIC(22,10) ,
  isreturnlog  NUMERIC(22) ,
  origionexchangeitem  VARCHAR(38) ,
  operateterminal  VARCHAR(38) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  accreditid  NUMERIC(22,19) ,
  operateemployeename  VARCHAR(64) ,
  logtime  DATE ,
  operateemployee  VARCHAR(38) ,
  inperiod  VARCHAR(38) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_mall_exchangeitemlog  is '无';
DROP TABLE IF EXISTS ods.ods_mall_goodbase ;
CREATE  TABLE ods.ods_mall_goodbase
(   id  VARCHAR(38) NOT NULL ,
  goodname  VARCHAR(100) ,
  specifications  VARCHAR(256) ,
  memorycode  VARCHAR(64) ,
  goodno  VARCHAR(64) ,
  isreal  NUMERIC(22) ,
  measure  VARCHAR(38) ,
  suggestsellprice  NUMERIC(22,19) ,
  purchaseprice  NUMERIC(22,19) ,
  notes  VARCHAR(256) ,
  goodstype  NUMERIC(22,10) ,
  gclass  VARCHAR(38) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  createtime  DATE ,
  extendgoodsid  VARCHAR(38) ,
  salemode  NUMERIC(22,10) ,
  isalloweditprice  NUMERIC(22) ,
  isneedauth  NUMERIC(22) ,
  goodsgroup  VARCHAR(38) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) ,
  etl_lad_dte DATE 
) 
partition by range (etl_lad_dte) 
  ( START (date '2017-05-03') INCLUSIVE 
  END (date '2019-09-23') INCLUSIVE EVERY (INTERVAL '1 month'), 
  DEFAULT PARTITION extra);
 comment on  table ods.ods_mall_goodbase  is '兑换单明细';
DROP TABLE IF EXISTS ods.ods_mall_goodext ;
CREATE  TABLE ods.ods_mall_goodext
(   id  VARCHAR(38) NOT NULL ,
  good  VARCHAR(38) ,
  futureland__cost  NUMERIC(22,19) ,
  purchase  VARCHAR(38) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  isbottomlinenotice  NUMERIC(22) ,
  bottomlinenum  NUMERIC(22,19) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_mall_goodext  is '无';
DROP TABLE IF EXISTS ods.ods_mall_goodsstock ;
CREATE  TABLE ods.ods_mall_goodsstock
(   id  VARCHAR(38) NOT NULL ,
  stock  VARCHAR(38) ,
  goods  VARCHAR(38) ,
  amount  NUMERIC(22,19) ,
  avgprice  NUMERIC(22,19) ,
  lastinprice  NUMERIC(22,19) ,
  totle  NUMERIC(22,19) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  createtime  DATE ,
  freezeamount  NUMERIC(22,19) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) ,
  etl_lad_dte DATE 
) 
partition by range (etl_lad_dte) 
  ( START (date '2017-05-03') INCLUSIVE 
  END (date '2019-09-23') INCLUSIVE EVERY (INTERVAL '1 month'), 
  DEFAULT PARTITION extra);
 comment on  table ods.ods_mall_goodsstock  is '商品分组设置';
DROP TABLE IF EXISTS ods.ods_mall_mall ;
CREATE  TABLE ods.ods_mall_mall
(   id  VARCHAR(38) NOT NULL ,
  mallname  VARCHAR(64) ,
  address  VARCHAR(256) ,
  ismaster  NUMERIC(22) ,
  mallcode  VARCHAR(64) ,
  connectip  VARCHAR(64) ,
  issys  NUMERIC(22) ,
  isenable  NUMERIC(22) ,
  lasteditemployee  VARCHAR(64) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  memcode  VARCHAR(64) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  createtime  DATE ,
  appversion  VARCHAR(64) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) );
 comment on  table ods.ods_mall_mall  is '级别会员卡对应商品';
DROP TABLE IF EXISTS ods.ods_mall_stockmothinoutsnap ;
CREATE  TABLE ods.ods_mall_stockmothinoutsnap
(   id  VARCHAR(38) NOT NULL ,
  goodsname  VARCHAR(64) ,
  goodsno  VARCHAR(64) ,
  goods  VARCHAR(38) ,
  stockname  VARCHAR(64) ,
  stock  VARCHAR(38) ,
  periodamount  NUMERIC(22,19) ,
  periodmoney  NUMERIC(22,19) ,
  inamount  NUMERIC(22,19) ,
  inmoney  NUMERIC(22,19) ,
  outamount  NUMERIC(22,19) ,
  outmoney  NUMERIC(22,19) ,
  traninamount  NUMERIC(22,19) ,
  traninmoney  NUMERIC(22,19) ,
  tranoutamount  NUMERIC(22,19) ,
  tranoutmoney  NUMERIC(22,19) ,
  saleamount  NUMERIC(22,19) ,
  salemoney  NUMERIC(22,19) ,
  checkamount  NUMERIC(22,19) ,
  checkmoney  NUMERIC(22,19) ,
  totalamount  NUMERIC(22,19) ,
  totalmoney  NUMERIC(22,19) ,
  operateterminal  VARCHAR(38) ,
  summary  VARCHAR(256) ,
  isdelete  NUMERIC(22) ,
  accreditid  NUMERIC(22,19) ,
  operateemployeename  VARCHAR(64) ,
  logtime  DATE ,
  operateemployee  VARCHAR(38) ,
  inperiod  VARCHAR(38) ,
  ownedmall  VARCHAR(38) ,
  ownedbusiness  VARCHAR(38) ,
  updatetime  DATE ,
  inoutmonth  NUMERIC(22,10) ,
  infa_createdate  DATE ,
  infa_updatedate  DATE ,
  infa_remark  VARCHAR(38) ,
  etl_lad_dte DATE 
) 
partition by range (etl_lad_dte) 
  ( START (date '2017-05-03') INCLUSIVE 
  END (date '2019-09-23') INCLUSIVE EVERY (INTERVAL '1 month'), 
  DEFAULT PARTITION extra);
 comment on  table ods.ods_mall_stockmothinoutsnap  is '无';
